### ISSUE TITLE
How to fix the _DeepMimic problem?

### ISSUE THREAD

**Issue by Lr-2002** [xbpeng/DeepMimic#166] opened 2021-11-28 08:32 UTC
I'm new here and faced the problem 
when running 
`python DeepMimic.py --arg_file args/play_motion_humanoid3d_args.txt ` at `/DeepMimic` dir

facing the problem 
```
ModuleNotFoundError: No module named '_DeepMimicCore'
```

and it was fixed by 

go to the `DeepMimicCore` dir and `cp _DeepMimicCore.so ../` to copy the so file to the home dir 

and then process `python DeepMimic.py --arg_file args/play_motion_humanoid3d_args.txt ` 

writting to record.

**Comment by rohit-kumar-j** [comment] 2021-11-28 17:11
Yes, the problem with file paths. If the problem is solved, you could close the issue perhaps

**Comment by Lr-2002** [comment] 2021-11-29 00:43
ok 
thanks for reply

**Closed** 2021-11-29 00:43 UTC
